---
- hosts: 172.31.11.169
  become: yes
  tasks:
  -  name: install git
     apt:
       name: git
       state: present
    
  -  name: install wget
     apt: 
       name: wget
       stateee: present
     

  -  name: install tree
     apt: 
       name: tree
       state: present
    