---
- hosts: 172.31.11.169
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy static file into ansible nodes
    copy:
      src: mytestfile
      dest: /home/ubuntu/mystaticfile
  - name: install webserver
    apt:
      name: apache2
      state: present
  - name: copy dynamic file into ansible nodes
    template:
      src: myindex
      dest: /var/www/html/index.html