---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install webserver on ubuntu ansible nodes
    apt:
      name: "{{webserverpackonubuntu}}"
      state: present
    when: ansible_os_family== "Debian" 

  - name: start webserver on ubuntu ansible nodes
    service:
      name: "{{webserverpackonubuntu}}"
      state: started    
    when: ansible_os_family== "Debian"  

  - name: install webserver on RedHat ansible nodes
    yum:
      name: "{{webserverpackonredhat}}"
      state: present
    when: ansible_os_family== "RedHat" 

  - name: start webserver on RedHat ansible nodes
    service:
      name: "{{webserverpackonredhat}}"
      state: started
    when: ansible_os_family == "RedHat"  